language: ruby
cache: bundler
install: bundle install --jobs=3 --retry=3 --without production development --path vendor/bundle
cache:
  directories:
  - vendor/bundle
rvm:
  - 2.2.0
  - 1.9.3
env:
  global:
    - COVERALLS_NOISY=true
  matrix:
    - DB=sqlite
    - DB=postgresql
before_script:
  - psql -c 'create database e_register' -U postgres
  - cp config/travis_database.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - bundle exec rspec spec
