language: ruby
rvm:
  - 2.2.0
  - 1.9.3
env:
  - DB=sqlite
  - DB=postgresql
before_script:
  - psql -c 'create database e-register' -U postgres
  - cp config/travis_database.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - bundle exec rspec spec